# Generated by Django 3.2.5 on 2021-07-19 15:42

import askcompany.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=askcompany.utils.uuid_upload_to),
        ),
    ]
